config/routes.rb
Rails.application.routes.draw do

  root to: 'hires#index'

  devise_for :users
  resources :hires

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id      :integer          not null, primary key
#  name    :string(255)
#  address :text(65535)
#

class Group < ApplicationRecord
  has_many :users
  has_many :hires
end

app/models/hire.rb
# == Schema Information
#
# Table name: hires
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  group_id       :integer
#  collect_date   :datetime
#  return_date    :datetime
#  status         :integer
#  band           :integer
#  reference      :text(65535)
#  invoice_number :integer
#

class Hire < ApplicationRecord
  belongs_to :user
  belongs_to :group

  has_many :loans
  has_many :ordered_sizes
  enum status: [:not_collected, :collected, :returned, :not_returned, :lost, :other]
  scope :collected_before, ->(time) { where("collect_date < ?", time) }
  scope :collected_after, ->(time) { where("collect_date > ?", time) }

  scope :returned_before, ->(time) { where("return_date < ?", time) }
  scope :returned_after, ->(time) { where("return_date > ?", time) }

  scope :collected_between, ->(collected_from, collected_to) { where("collect_date BETWEEN ? AND ?", collected_from, collected_to) }
  scope :returned_between, ->(returned_from, returned_to) { where("return_date BETWEEN ? AND ?", returned_from, returned_to) }

  def past_hires
    self.returned_before(Date.today)
  end
end

app/models/loan.rb
# == Schema Information
#
# Table name: loans
#
#  id         :integer          not null, primary key
#  hire_id    :integer
#  name_tag   :string(255)
#  date_out   :datetime
#  date_back  :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Loan < ApplicationRecord
  belongs_to :hire
end

app/models/ordered_size.rb
# == Schema Information
#
# Table name: ordered_sizes
#
#  id      :integer          not null, primary key
#  hire_id :integer
#  request :integer
#  booked  :integer
#

class OrderedSize < ApplicationRecord

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  group_id               :integer
#  role                   :string(255)
#  username               :string(255)
#  name                   :string(255)
#  surname                :string(255)
#  telephone              :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string(255)
#  locked_at              :datetime
#  approved               :boolean          default(FALSE), not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  belongs_to :group
  has_many :hires, through: :group

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/hires_controller.rb
class HiresController < ApplicationController
  before_action :set_account, only: [:show, :update, :edit]
  before_action :redirect_non_registered

  respond_to :html, :json

  def index

    if params[:approved] == "false"
        @users = User.where(approved: false)
    else
        @users = User.all
    end




    # Copy of current for the moment
    @Hires = Hire.all
    @Past_Hires = past_hires(@Hires)
    @Past_Hires ||= []

    @Current_Hires = current_hires(@Hires)

    @Future_Hires = future_hires(@Hires)
    respond_with(@Hires)
  end

  def new
    @Hire = Hire.new
  end

  def create
    @Hire = Hire.create(hire_params)
    @Hire.update(user_id: current_user.id)
    @Hire.update(group_id: current_user.group_id)

    if @Hire.save
      flash[:success] = "Created successfully"
      redirect_to @Hire
    else
      render 'new'
    end

  end
  def show

  end

  def update

    if @Hire.update(hire_params)
      redirect_to @Hire
    else
      render 'index'
    end
  end

  def edit
  end

  def past_hires(hire)
    hire.returned_before(Date.today)
  end

  def current_hires(hire)
    #Collection day today or less AND returning day larger than today
    # current from before today and returned after (hardcoded) 1 year
    hires = hire.collected_before(Date.today)
    hires = hires.returned_after(Date.today)
  end

  def future_hires(hire)
    hires = hire.collected_after(Date.today)
    hires = hires.returned_after(2.years)
  end

  def set_account
    @Hire = Hire.find(params[:id]) 
  end

  private

  def hire_params
    params.require(:hire).permit(:collect_date, :return_date, :status, :band, :reference, :invoice_number, :user_id, :group_id)
  end


  def redirect_non_registered
    authenticate_user!
    redirect_to root_path if !current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
#  def header(text)
#    content_for(:header) {text.to_s}
#  end
end

app/helpers/hires_helper.rb
module HiresHelper
end

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/hires/_form_fields.html.erb
<%= form_for(@Hire) do |f| %>
  <p>
  <%= f.label :collect_date %>
  <%= f.date_field :collect_date %>
  </p>

  <p>
  <%= f.label :return_date %>
  <%= f.date_field  :return_date %>
  </p>

  <p>
  <%= f.label :status %> 
  <%= f.text_field :status %>
  </p>

  <p>
  <%= f.label :band %>
  <%= f.text_field :band %>
  </p>

  <p>
  <%= f.label :reference %>
  <%= f.text_field :reference %>
  </p>

  <p>
  <%= f.label :invoice_number %>
  <%= f.text_field :invoice_number %>
  </p>

  <p>
  <%= f.submit "Save Changes" %>
  </p>
<% end %>

app/views/hires/current.html.erb
<h1>Hires#current</h1>

<% @Hires.each do |hire| %>
  <ul>
    <li><strong>Username: </strong><%= hire.user.username %></li>
    <li><strong>Group: </strong><%= hire.group.name %></li>
    <li><strong>Status: </strong><%= hire.status %></li>
    <li><strong>Band: </strong><%= hire.band %></li>
    <li><strong>Invoice Number: </strong><%= hire.invoice_number %></li>
    <br>
    <li><strong>Collect Date: </strong><%= hire.collect_date.strftime("%d-%b-%Y") %></li>
    <li><strong>Return Date: </strong><%= hire.return_date.strftime("%d-%b-%Y") %></li>
    <br> 
    <li><strong>Reference: </strong><%= hire.reference %></li>
  </ul>
<% end %>

app/views/hires/edit.html.erb
<h1>Update your Profile</h1>

<%= form_for @Hire do |f| %>
  <%= render 'shared/form_errors', object: @Hire %>

  <%= render 'form_fields', f: f %>
<% end %>

app/views/hires/future.html.erb
<h1>Hires#future</h1>

<% @Hires.each do |hire| %>
  <ul>
    <li><strong>Username: </strong><%= hire.user.username %></li>
    <li><strong>Group: </strong><%= hire.group.name %></li>
    <li><strong>Status: </strong><%= hire.status %></li>
    <li><strong>Band: </strong><%= hire.band %></li>
    <li><strong>Invoice Number: </strong><%= hire.invoice_number %></li>
    <br>
    <li><strong>Collect Date: </strong><%= hire.collect_date.strftime("%d-%b-%Y") %></li>
    <li><strong>Return Date: </strong><%= hire.return_date.strftime("%d-%b-%Y") %></li>
    <br> 
    <li><strong>Reference: </strong><%= hire.reference %></li>
  </ul>
<% end %>

app/views/hires/index.html.erb
<h1>Past Hires</h1>








<% @users.each do |user| %>
  <p><%= user.email %></p>
  <p><%= user.approved %></p>
  <p><%= user.username %></p>
  <%= link_to "Users awaiting approval", :action => "index", :approved => "false" %>
<% end %>


<%= link_to "Create new Hire", new_hire_path %>
<%= link_to "Log out", destroy_user_session_path, method: :delete %>
<% @Past_Hires.each do |hire| %>
  <ul>
    <li><strong>Username: </strong><%= hire.user.username %></li>
    <li><strong>Group: </strong><%= hire.group.name %></li>
    <li><strong>Status: </strong><%= hire.status %></li>
    <li><strong>Band: </strong><%= hire.band %></li>
    <li><strong>Invoice Number: </strong><%= hire.invoice_number %></li>
    <br>
    <li><strong>Collect Date: </strong><%= hire.collect_date.strftime("%d-%b-%Y") %></li>
    <li><strong>Return Date: </strong><%= hire.return_date.strftime("%d-%b-%Y") %></li>
    <br> 
    <li><strong>Reference: </strong><%= hire.reference %></li>
    <li><%= link_to "visit", hire_path(hire)%></li>
  </ul>
<% end %>



<h1>Current Hires</h1>

<% @Current_Hires.each do |hire| %>
  <ul>
    <li><strong>Username: </strong><%= hire.user.username %></li>
    <li><strong>Group: </strong><%= hire.group.name %></li>
    <li><strong>Status: </strong><%= hire.status %></li>
    <li><strong>Band: </strong><%= hire.band %></li>
    <li><strong>Invoice Number: </strong><%= hire.invoice_number %></li>
    <br>
    <li><strong>Collect Date: </strong><%= hire.collect_date.strftime("%d-%b-%Y") %></li>
    <li><strong>Return Date: </strong><%= hire.return_date.strftime("%d-%b-%Y") %></li>
    <br> 
    <li><strong>Reference: </strong><%= hire.reference %></li>
    <li><%= link_to "visit", hire_path(hire)%></li>
  </ul>
<% end %>

<h1>Future Hires</h1>

<% @Future_Hires.each do |hire| %>
  <ul>
    <li><strong>Username: </strong><%= hire.user.username %></li>
    <li><strong>Group: </strong><%= hire.group.name %></li>
    <li><strong>Status: </strong><%= hire.status %></li>
    <li><strong>Band: </strong><%= hire.band %></li>
    <li><strong>Invoice Number: </strong><%= hire.invoice_number %></li>
    <br>
    <li><strong>Collect Date: </strong><%= hire.collect_date.strftime("%d-%b-%Y") %></li>
    <li><strong>Return Date: </strong><%= hire.return_date.strftime("%d-%b-%Y") %></li>
    <br>
    <li><strong>Reference: </strong><%= hire.reference %></li>
    <li><%= link_to "visit", hire_path(hire)%></li>
  </ul>
<% end %>

app/views/hires/new.html.erb
<%= form_for @Hire do |f| %>
  <%= render 'shared/form_errors', object: @Hire %>

  <%= render 'form_fields', f: f %>
<% end %>

app/views/hires/past.html.erb
<h1>Hires#past</h1>
<p>Find me in app/views/hires/past.html.erb</p>
<% @Hires.each do |hire| %>
  <ul>
    <li><strong>Username: </strong><%= hire.user.username %></li>
    <li><strong>Group: </strong><%= hire.group.name %></li>
    <li><strong>Status: </strong><%= hire.status %></li>
    <li><strong>Band: </strong><%= hire.band %></li>
    <li><strong>Invoice Number: </strong><%= hire.invoice_number %></li>
    <br>
    <li><strong>Collect Date: </strong><%= hire.collect_date.strftime("%d-%b-%Y") %></li>
    <li><strong>Return Date: </strong><%= hire.return_date.strftime("%d-%b-%Y") %></li>
    <br> 
    <li><strong>Reference: </strong><%= hire.reference %></li>
  </ul>
<% end %>

app/views/hires/show.html.erb
<%= @Hire.reference%>
<%= link_to "Update", edit_hire_path(@Hire)%>
<%= link_to "back", hires_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Fota</title>
<%= csrf_meta_tags %>

<!--  < stylesheet_pack_tag 'hello_vue' %> -->
<!--  < javascript_pack_tag 'hello_vue' %> -->

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield  %>
</body>
</html>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <p><%= pluralize(object.errors.count, "error") %> prohibited this from saving:</p>

    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>